export type ActionTypes =
  | "GET_PUBLICATIONS"
  | "POST_PUBLICATION"
  | "USER_REGISTER_REQUEST"
  | "USER_REGISTER_SUCCESS"
  | "USER_REGISTER_FAIL"
  | "USER_SIGNIN_REQUEST"
  | "USER_SIGNIN_SUCCESS"
  | "USER_SIGNIN_FAIL";
